sudo: required
services: -docker
before_install:
  - docker-compose build
# script:
#   - docker run choton654/nest-next-graphql npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'docker'
  env: 'docker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-013225200604'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
