version: '3.4'

services:
  mongo:
    container_name: mymongo
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  redis:
    container_name: rdb
    image: redis
    ports:
      - 6379:6379

volumes:
  mongo:
